server:
  port: 8083

spring:
  application:
    name: book-store
  main:
    web-application-type: reactive
  r2dbc:
    url: ${R2DBC:r2dbc:postgresql://localhost:5432/book_store_db}
    username: postgres
    password: postgres
    pool:
      enabled: true
      initial-size: 5
      max-size: 10
  liquibase:
    url: ${JDBC:jdbc:postgresql://localhost:5432/book_store_db}
    user: postgres
    password: postgres
    enabled: true
    change-log: classpath:liquibase/master.xml
  webflux:
    problemdetails:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.r2dbc: DEBUG
    liquibase: DEBUG